### ISSUE TITLE
LECIF without CAGE data

### ISSUE THREAD

**Issue by RocesV** [ernstlab/LECIF#1]
Hi everyone! 

First of all thank you for this amazing software. I am currently trying to implement LECIF to two model plant species. I have chromatin states, DNaseChIPseq anda RNAseq data but CAGE data is not available. I could complete all steps until source/generateDataThreaded.py script that requires CAGE data arguments (dir and number of features). 

Is there any possibility of obtaining a LECIF version/modification that does not need CAGE data in order to implement it to my organisms of interest?

Thank you very much in advance 😄 
RocesV

**Comment by kwonsoobin** [comment]
Thanks for reaching out! We currently do not have a version that does not require CAGE data. As a workaround, you can try the following:
- Create a directory with an empty text file: `mkdir CAGE; touch CAGE/dummy.txt`
- When calling `source/generateDataThreaded.py`, provide that as CAGE directory and set the number of CAGE experiments to 0: `--cage-dir CAGE --cage-num-experiments 0` 

Please let us know if you encounter further issues.
